### ISSUE TITLE
Check Implementation

### ISSUE THREAD

**Issue by Fredster64** [sachin3796/Chess#4]
**Is your feature request related to a problem? Please describe.**
I've had an idea as to how 'check' can be implemented in the project. It might need some work but I thought I'd let you know :) I'll start working on it in my fork if it gets the green light from you. 

**Describe the solution you'd like**
My idea is that, instead of having to remove disallowed moves from the vector of potential moves (which sounds like it could be a little tricky), we can instead make a move, check whether or not the player who has moved is _still in check_ after the move and, if they are, we can revert the board back to how it was before the move, print some kind of "You can't do that, you'd still be in check!" message, and then prompt the player to try a different move instead. 

As I said, if you want me to I'll start working on it in my fork :)

**Comment by sachin3796** [comment]
Your solution is much easier than mine, completely overthought the obvious! If you would like to work on it, go ahead and I can start working on finishing the game rules. Sorry about the current state of the code, I have been redefining lots of things for readability and because I get easily confused, plus the interface required a few methods to get shuffled about.

**Comment by sachin3796** [comment]
Hello @Fredster64 
I just want to make you aware of some things:

- Good news: The rules have been completed - everything has been implemented on my side, bar 'Check'; it looks like you have made some good progress over it so far!
- The problem is that I have made many changes to the current code, and so there will undoubtedly be merge conflicts. Hopefully it shouldn't be too difficult to sort out, but I will postpone working on the project any more until you are happy with your solution so we can merge into the "check" branch I have made.
- Also, I am unsure if the Castling needs to be adjusted for the 'Check' case. Hopefully this is an easy fix, but I am not expecting it to be the case.

Looks like there is not too much left to go, so thanks for contributing your ideas! They have been exceptionally helpful!

**Comment by sachin3796** [comment]
Oh it looks like you have just sent me the pull request, so ignore the part about postponing haha!

**Comment by sachin3796** [comment]
Hi, I am currently experiencing a bug where it changes the player if the player made an invalid move while in Check. Should be quite easy to fix, but I am not going to push to Master until this gets fixed - instead I will be working from the 'check' branch, and you are welcome to fork that if you would like.
